name: Execute notebook

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install Papermill
        run: pip install papermill
      - name: Run notebook
        run: papermill --progress-bar --log-level DEBUG lecture_0.ipynb /dev/null
